export interface PacienteData {
  nombrePaciente: string,
  alergias: string,
  sexo: string,
  fechaNacimiento: string,
  correo: string,
  telefono: string,
  foto: string,
  nombre: string,
  primer_apellido: string,
  segundo_apellido: string,
  estatura: float,
  peso: float,
  imc: float,
}