import './globals.css';
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Nutrilud",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navbar />
        <div className="flex-1 p-4 pt-2">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}