name: Deploy Nutrilud FrontEnd

on:
    pull_request:
        branches:
            - master

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Setup SSH Connection
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.EC2_HOST }}
                username: ${{ secrets.EC2_USER }}
                key: ${{ secrets.EC2_KEY }}
                script: |
                    pm2 stop nutrilud-frontend
                    
                    rm -rf Nutrilud-FrontEnd-
                    git clone https://github.com/AbrahamCoco/Nutrilud-FrontEnd-.git
                    cd Nutrilud-FrontEnd-

                    npm ci
                    npm run build
                    cd ..

                    pm2 start nutrilud-frontend



